In [1]:
import pandas as pd 
import numpy as np 
import matplotlib.pyplot as plt 
import seaborn as sns

In [2]:
df = pd.read_csv("df_model_data_full.csv")

In [3]:
df.head()

   hour  day  lon_bin  lat_bin  congestion
0     0    0       23       88           5
1     0    0       24       88          10
2     0    0       25       87           2
3     0    0       25       88           2
4     0    0       26       78           5

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 87128 entries, 0 to 87127
Data columns (total 5 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   hour        87128 non-null  int64
 1   day         87128 non-null  int64
 2   lon_bin     87128 non-null  int64
 3   lat_bin     87128 non-null  int64
 4   congestion  87128 non-null  int64
dtypes: int64(5)
memory usage: 3.3 MB

In [5]:
df.describe()

               hour           day       lon_bin       lat_bin     congestion
count  87128.000000  87128.000000  87128.000000  87128.000000   87128.000000
mean      11.825578      3.067854     47.798308     67.718300     956.968793
std        6.020256      1.972677     18.593457     17.426332    7055.431774
min        0.000000      0.000000      0.000000      0.000000       1.000000
25%        7.000000      1.000000     36.000000     63.000000       5.000000
50%       11.000000      3.000000     44.000000     73.000000      11.000000
75%       17.000000      5.000000     55.000000     77.000000      38.000000
max       23.000000      6.000000    100.000000    100.000000  174974.000000